DjangoApp2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pdfmr/', include('pdfmr.urls')),
    path('', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

pdfmr/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "pdfmr"

urlpatterns = [
    path('top/', views.top, name='top'),
    path('upload/', views.UploadView.as_view(), name='upload'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    """ログオンフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

pdfmr/forms.py
from django import forms
from django.conf import settings
from django.core.files.storage import default_storage
import os
import random
import string


class UploadForm(forms.Form):
    """PDFアップロード用フォームの定義
       saveメソッドはアップロードしたPDFを一時フォルダに保存する。
    """
    document = forms.FileField(label="PDFアップロード",
                               widget=forms.ClearableFileInput(
                                   attrs={'multiple': True}),
                               )

    def save(self):
        upload_files = self.files.getlist('document')
        temp_dir = os.path.join(settings.MEDIA_ROOT,
                                self.create_dir(10))  # 一時フォルダの生成
        for pdf in upload_files:
            default_storage.save(os.path.join(
                temp_dir, pdf.name), pdf)  # 一時フォルダにPDFを保存
        return temp_dir

    def create_dir(self, n):
        """一時フォルダ名生成関数"""
        return 'pdf\\' + ''.join(random.choices(string.ascii_letters + string.digits, k=n))

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(LoginView, LogoutView)
from .forms import LoginForm


class Login(LoginView):
    form_class = LoginForm
    template_name = 'accounts/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'accounts/login.html'

pdfmr/views.py
from django.shortcuts import render
from django.views import generic  # FormViewを利用するため
from django.contrib.auth.mixins import LoginRequiredMixin   # ログオンユーザのみアクセス可とするために利用する
from django.conf import settings  # settings.pyの定義内容を利用するため
from .forms import UploadForm   # forms.pyで定義したUploadFormをインポート
# ファイルオブジェクト操作のためdefault_storageを利用する
from django.core.files.storage import default_storage
import shutil
import os

# Create your views here.


def top(requests):
    return render(requests, 'pdfmr/top.html')


class UploadView(LoginRequiredMixin, generic.FormView):
    form_class = UploadForm
    template_name = 'pdfmr/upload_form.html'

    def form_valid(self, form):
        user_name = self.request.user.username  # ログオンユーザ名の取得
        user_dir = os.path.join(settings.MEDIA_ROOT,
                                "excel", user_name)  # ユーザディレクトリパスの生成
        if not os.path.isdir(user_dir):  # ユーザディレクトリの作成
            os.makedirs(user_dir)
        temp_dir = form.save()  # upload一時フォルダの取得
        # pdf -> PDF⇒excel変換処理の実行（あとで実装）
        shutil.rmtree(temp_dir)  # upload一時フォルダの削除
        _, file_list = default_storage.listdir(
            os.path.join(settings.MEDIA_ROOT, "excel", user_name))
        message = "正常終了しました。"
        context = {
            'file_list': file_list,
            'user_name': user_name,
            'message': message,
        }
        return render(self.request, 'pdfmr/complete.html', context)

    def form_invalid(self, form):
        return render(self.request, 'pdfmr/upload_form.html', {'form': form})

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>PDFtoExcel</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" />
        <!-- Bootstrap 3.3.7 -->
        <link
            rel="stylesheet"
            href="{% static 'AdminLTE-3.0.2/bower_components/bootstrap/dist/css/bootstrap.min.css' %}"
        />
        <!-- Font Awesome -->
        <link
            rel="stylesheet"
            href="{% static 'AdminLTE-3.0.2/bower_components/font-awesome/css/font-awesome.min.css' %}"
        />
        <!-- Ionicons -->
        <link rel="stylesheet" href="{% static 'AdminLTE-3.0.2/bower_components/Ionicons/css/ionicons.min.css' %}" />
        <!-- Theme style -->
        <link rel="stylesheet" href="{% static 'AdminLTE-3.0.2/dist/css/AdminLTE.min.css' %}" />
        <!-- iCheck -->
        <link rel="stylesheet" href="{% static 'AdminLTE-3.0.2/plugins/iCheck/square/blue.css' %}" />

        <!-- Google Font -->
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic"
        />
    </head>
    <body class="hold-transition login-page">
        <div class="login-box">
            <div class="login-logo">
                <b>PDFtoExcel</b>
            </div>
            <!-- /.login-logo -->
            <div class="login-box-body">
                <p class="login-box-msg"><b>ログオン画面</b></p>

                <form action="" method="POST">
                    {% csrf_token %} {% for field in form %}
                    <div class="form-group has-feedback">
                        {{ field }}
                    </div>
                    {% endfor %}
                    <div class="row">
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            <p>{{ error }}</p>
                        </div>
                        {% endfor %}
                        <!-- /.col -->
                        <div class="col-xs-4">
                            <button type="submit" class="btn btn-primary btn-block btn-flat">ログオン</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>
            </div>
            <!-- /.login-box-body -->
        </div>
        <!-- /.login-box -->

        <!-- jQuery 3 -->
        <script src="{% static 'AdminLTE-3.0.2/bower_components/jquery/dist/jquery.min.js' %}"></script>
        <!-- Bootstrap 3.3.7 -->
        <script src="{% static 'AdminLTE-3.0.2/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <!-- iCheck -->
        <script src="{% static 'AdminLTE-3.0.2/plugins/iCheck/icheck.min.js' %}"></script>
    </body>
</html>

templates/pdfmr/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>AdminLTE 3 | Dashboard</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{% static 'AdminLTE-3.0.2/plugins/fontawesome-free/css/all.min.css' %}" />
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
        <!-- Tempusdominus Bbootstrap 4 -->
        <link
            rel="stylesheet"
            href="{% static 'AdminLTE-3.0.2/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}"
        />
        <!-- iCheck -->
        <link rel="stylesheet" href="{% static 'AdminLTE-3.0.2/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}" />
        <!-- JQVMap -->
        <link rel="stylesheet" href="{% static 'AdminLTE-3.0.2/plugins/jqvmap/jqvmap.min.css' %}" />
        <!-- Theme style -->
        <link rel="stylesheet" href="{% static 'AdminLTE-3.0.2/dist/css/adminlte.min.css' %}" />
        <!-- overlayScrollbars -->
        <link
            rel="stylesheet"
            href="{% static 'AdminLTE-3.0.2/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}"
        />
        <!-- Daterange picker -->
        <link rel="stylesheet" href="{% static 'AdminLTE-3.0.2/plugins/daterangepicker/daterangepicker.css' %}" />
        <!-- summernote -->
        <link rel="stylesheet" href="{% static 'AdminLTE-3.0.2/plugins/summernote/summernote-bs4.css' %}" />
        <!-- Google Font: Source Sans Pro -->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet" />
    </head>
    <body class="hold-transition sidebar-mini layout-fixed">
        <div class="wrapper">
            <!-- Navbar -->
            <nav class="main-header navbar navbar-expand navbar-white navbar-light">
                <!-- Left navbar links -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                    </li>
                </ul>

                <!-- SEARCH FORM -->

                <!-- Right navbar links -->
                <ul class="navbar-nav ml-auto">
                    <!-- Messages Dropdown Menu -->
                    {% if user.is_authenticated %}
                    <li>
                        <a class="nav-link">ユーザ名：{{ user.get_username }}</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'accounts:logout' %}">
                            <i class="fa fa-fw fa-sign-out"></i>ログアウト
                        </a>
                    </li>
                    {% endif %}
                    <!-- Notifications Dropdown Menu -->
                </ul>
            </nav>
            <!-- /.navbar -->

            <!-- Main Sidebar Container -->
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <!-- Brand Logo -->
                <a href="index3.html" class="brand-link">
                    <span class="brand-text font-weight-light">AdminLTE </span>
                </a>

                <!-- Sidebar -->
                <div class="sidebar">
                    <!-- Sidebar user panel (optional) -->

                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul
                            class="nav nav-pills nav-sidebar flex-column"
                            data-widget="treeview"
                            role="menu"
                            data-accordion="false"
                        >
                            <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                            <li class="nav-item has-treeview menu-open">
                                <a href="#" class="nav-link active">
                                    <i class="nav-icon fas fa-tachometer-alt"></i>
                                    <p>
                                        ダッシュボード
                                        <i class="right fas fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="{% url 'pdfmr:upload' %}" class="nav-link active">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>PDFアップロード</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="./index2.html" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Excel管理画面</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
                <!-- /.sidebar -->
            </aside>

            {% block content %} {% endblock %}

            <!-- /.content-wrapper -->
            <footer class="main-footer">
                <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
                All rights reserved.
                <div class="float-right d-none d-sm-inline-block"><b>Version</b> 3.0.2</div>
            </footer>

            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Control sidebar content goes here -->
            </aside>
            <!-- /.control-sidebar -->
        </div>
        <!-- ./wrapper -->

        <!-- jQuery -->
        <script src="{% static 'AdminLTE-3.0.2/plugins/jquery/jquery.min.js' %}"></script>
        <!-- jQuery UI 1.11.4 -->
        <script src="{% static 'AdminLTE-3.0.2/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script>
            $.widget.bridge('uibutton', $.ui.button);
        </script>
        <!-- Bootstrap 4 -->
        <script src="{% static 'AdminLTE-3.0.2/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <!-- ChartJS -->
        <script src="{% static 'AdminLTE-3.0.2/plugins/chart.js/Chart.min.js' %}"></script>
        <!-- Sparkline -->
        <script src="{% static 'AdminLTE-3.0.2/plugins/sparklines/sparkline.js' %}"></script>
        <!-- JQVMap -->
        <script src="{% static 'AdminLTE-3.0.2/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
        <script src="{% static 'AdminLTE-3.0.2/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
        <!-- jQuery Knob Chart -->
        <script src="{% static 'AdminLTE-3.0.2/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
        <!-- daterangepicker -->
        <script src="{% static 'AdminLTE-3.0.2/plugins/moment/moment.min.js' %}"></script>
        <script src="{% static 'AdminLTE-3.0.2/plugins/daterangepicker/daterangepicker.js' %}"></script>
        <!-- Tempusdominus Bootstrap 4 -->
        <script src="{% static 'AdminLTE-3.0.2/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
        <!-- Summernote -->
        <script src="{% static 'AdminLTE-3.0.2/plugins/summernote/summernote-bs4.min.js' %}"></script>
        <!-- overlayScrollbars -->
        <script src="{% static 'AdminLTE-3.0.2/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
        <!-- AdminLTE App -->
        <script src="{% static 'AdminLTE-3.0.2/dist/js/adminlte.js' %}"></script>
        <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
        <script src="{% static 'AdminLTE-3.0.2/dist/js/pages/dashboard.js' %}"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="{% static 'AdminLTE-3.0.2/dist/js/demo.js' %}"></script>
    </body>
</html>

templates/pdfmr/complete.html
{% extends './base.html' %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>一覧画面</h1>
  <ol class="breadcrumb">
    <li><a href="{% url 'pdfmr:top' %}"><i class="fa fa-dashboard"></i> ホーム</a></li>
    <li class="active">ダッシュボード</li>
  </ol>
</section>
<!-- Main content -->
<section class="content">
<!-- Small boxes (Stat box) -->
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title"> <b>PDF→Excel変換処理結果</b></h3>
      </div>
      <div class="box-body">
        <div class="card-body">
          {% if message  %}
          <div class="callout callout-info">
            {{message}}
          </div>
          {% endif %}
        </div>
        <hr>
        <div class="text-center">
          <a href="{% url 'pdfmr:top' %}" class="btn btn-primary btn-sm" role="button">戻る</a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</section>
<!-- /.content -->
<!-- /.content-wrapper -->
{% endblock content %}

templates/pdfmr/top.html
{% extends './base.html' %} {% block content %}

<div class="content-wrapper">
    <section class="content-header">
        <h1>ダッシュボード</h1>
        <ol class="breadcrumb">
            <li>
                <a href="#"><i class="fa fa-dashboard"></i> ホーム /</a>
            </li>
            <li class="active">ダッシュボード</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-primary">
                    <div class="inner">
                        <h4>PDFtoExcel</h4>
                        <p>PDF→Excel変換</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-android-share"></i>
                    </div>
                    <a href="{% url 'pdfmr:upload' %}" class="small-box-footer"
                        >管理画面へ移動 <i class="fa fa-arrow-circle-right"></i
                    ></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h4>Excel管理画面</h4>
                        <p>生成済みExcelファイルの管理</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-document"></i>
                    </div>
                    <a href="#" class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-lg-7 connectedSortable"></section>
            <!-- /.Left col -->
            <!-- right col (We are only adding the ID to make the widgets sortable)-->
            <!-- right col -->
        </div>
        <!-- /.row (main row) -->
    </section>
    <!-- /.content -->
</div>

{% endblock content %}

templates/pdfmr/upload_form.html
{% extends './base.html' %} {% block content %}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>アップロード画面</h1>
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'pdfmr:top' %}"><i class="fa fa-dashboard"></i> ホーム</a>
            </li>
            <li class="active">ダッシュボード</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"><b>PDF->Excel変換</b></h3>
                        <p>※PDFは複数ファイルを一括でアップロードすることができます。</p>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <hr />
                        <form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <label class="col-lg-5 col-form-label"><h4>{{form.document.label}}</h4></label><br />
                            <div class="form-group col-sm-5">
                                {{form.document}}
                            </div>
                            <button type="submit" class="btn btn-sm btn-primary">アップロード</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<!-- /.content -->
<!-- /.content-wrapper -->
{% endblock content %}